Denner lindo
mateusbays/endpoint-CRUD pull request #1
Opened 2020-08-19 15:06 UTC by mateusbays

você vai ver isso?

2020-08-19 15:07 UTC, dlermen12 requested changes

2020-08-19 15:07 UTC, dlermen12 commented on src/main/java/com/example/demo/PersonController.java
> +        return "Post concluido";
Altera isso para ou retornar void ou retonar o próprio objecto, como você me faz um endpoint JSON que retorna uma STRING que não é JSON. Isso é meio sem noção!

2020-08-20 12:52 UTC, mateusbays reviewed
não tenho culpa que seja uma dependencia do android

2020-08-20 13:06 UTC, dlermen12 requested changes

2020-08-20 13:06 UTC, dlermen12 commented on pom.xml
> +            <artifactId>android-json</artifactId>
Remove essas lib, vc não esta usando Vaadin nem android

2020-08-20 13:06 UTC, dlermen12 commented on pom.xml
> +            <artifactId>android-json</artifactId>
Mesma coisa aqui remove isso

2020-08-20 13:06 UTC, dlermen12 commented on src/main/java/com/example/demo/PersonController.java
> +        return JSONObject.quote("Post concluido");
retorna apenas o objecto e o Spring transforma em JSON

Outra o Padrão de Json Converter do Spring é o ObjectMapper
não precisa add lib nem 1 ai

2020-08-20 13:39 UTC, mateusbays commented
Posso resolver dessa fora ou utilizando a classe ObjectMapper, assim está ok, mas enfim...

2020-08-25 13:04 UTC, dlermen12 approved these changes

2020-08-25 13:04 UTC, merged